const quiz = [{q:'React was developed by ______', options:['google','meta', 'microsoft','twitter'], answer:'meta'},
                    {q:'which of these is a search engine?', options:['google','chatgpt','chrome'], answer:'google'},
                    {q:'Chatbots and Chatgpt can be categorized as a search engine?', options:['true','false'], answer:'false'},
                    {q:'JavaScript was invented by ______', options:['Brendan Eich','Guido Van Rossum', 'Tim Berners-Lee', 'All of the above'], answer:'Brendan Eich'},
                    {q:'Reactjs is a ______', options:['library','add-on', 'framework','extension'], answer:'library'},
                    {q:'SpiderMonkey is a javaScript engine for______', options:['chrome','firefox', 'internet explorer','safari'], answer:'firefox'},
                    {q:'User Interface can be termed as _______', options:['backend development','web design', 'web development','frontend development'], answer:'frontend development'},
                    {q:'Choose the one-odd out', options:['php','nodejs', 'javascript','python'], answer:'javascript'},
                    {q:"A book titled 'simplified javascript for vips' was written by _______", options:['Elon musk','Wole Soyinka', 'Douglas Crockford', 'Ebenezer Don'], answer:'Ebenezer Don'},
                    {q:"What does this apparently symbolize in software development?", img:"../assets/bug.jpg" , options:['software testing','scanning', 'troubleshooting', 'debugging'], answer:'debugging'}]